### ISSUE TITLE
SIGILL when compiling and loading

### ISSUE THREAD

**Issue by sm2n** [marcoheisig/sb-simd#17] opened 2022-01-04 09:00 UTC
I am trying to load sb-simd commit 9072af618a3c35e02ea0331201ed685408d15b51 (latest at the time of posting) into sbcl 2.1.11, and it is crashing into ldb when it tries to compile `sb-simd/code/define-commutatives.lisp`.
```
 tid 15280 CPU state (SIGILL received): PC=537f859b Flags={IF ZF PF}
              rax              rcx              rdx              rbx              rsp              rbp              rsi              rdi
     7F16F0F98B40                2 FFFFFFFF00000019 FFFFFFFF00000019     7F16F0F93B20     7F16F0F93B30 FFFFFFFF00000019       1004AEF71F
               r8               r9              r10              r11              r12              r13              r14              r15
         50100110       1004AEF797             1F94       1004AEF797     55AD2EB3AB90     7F16F1198080     7F16F0F93B30     7F16F0F94757
                              xmm0                              xmm1                              xmm2                              xmm3
  000000000000000000000000FFFFFFFF  00007F16F0F93F5000007F16F0F98B30  00000000000000000000000040E00000  00000000000000000000000040E00000
                              xmm4                              xmm5                              xmm6                              xmm7
  1B188513A407A60D2F85100F84043D67  A61FA50DA41FA407A618A51F2E8407A6  22008414A402A401A20CA404A44CA407  07A6221A8507A614A507A623148504A4
                              xmm8                              xmm9                             xmm10                             xmm11
  03A43400840BA4062D022401A2042D0C  0000FF000000FFFFFF00FFFFFFFFFFFF  00000000000000000000000000000000  00000000000000008000000000000000
                             xmm12                             xmm13                             xmm14                             xmm15
  0000000000000000BFE5555555555560  00000000000000000000000000000000  00000000000000000000000000000000  00000000000000000000000000000000
sigmask=
fatal error encountered in SBCL pid 15261 tid 15280:
Unhandled SIGILL at 0x537f859b.

Error opening /dev/tty: No such device or address
Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> 
```
```
CL-USER> *features*
(:SLYNK :QUICKLISP :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)
```
```
$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
stepping	: 9
microcode	: 0x20
cpu MHz		: 1416.606
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts flush_l1d
vmx flags	: vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 5786.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

Please tell me if you would like some other information. Thanks.

**Comment by marcoheisig** [comment] 2022-01-04 10:06
This is a known issue.  Your Ivy Bridge CPU supports AVX but not AVX2, but he 256bit SIMD interface of SBCL was written with the assumption that such platforms don't exist or are not particularly relevant.  So SBCL uses AVX2 instructions in several places, and as soon as you reach such a place, your code SIGILLs.  In your case, the code that triggers the SIGILL is probably the vpcmpeqd instruction in load-int-avx2-immediate in `compiler/x86-64/simd-pack-256.lisp`.

I'd love to have that issue resolved, but it is somewhat involved.  I need to teach SBCL how to detect the presence or absence of instructions sets, and provide different paths depending on what is available.  A side constraint is that the performance of machines with AVX2 should not deteriorate.  And then there is this really tricky issue of what to do in the case where code is compiled on a machine with AVX2, then save-lisp-and-die'd, and moved to a machine without AVX2.  So the instruction sets being used should probably be a property of the source code, with lexical scope, and not just a property of what is available on the machine that runs compile-file.

I'll leave this issue open for others that run into the same problem.  And I'll think of a way to fix this properly in SBCL.  Thanks for reporting!

**Comment by sm2n** [comment] 2022-01-06 05:38
Thanks for the information.

> This is a known issue.  Your Ivy Bridge CPU supports AVX but not AVX2, but he 256bit SIMD interface of SBCL was written with the assumption that such platforms don't exist or are not particularly relevant.  So SBCL uses AVX2 instructions in several places, and as soon as you reach such a place, your code SIGILLs.  In your case, the code that triggers the SIGILL is probably the vpcmpeqd instruction in load-int-avx2-immediate in `compiler/x86-64/simd-pack-256.lisp`.

Ah, I see the dependency comment in the code there. I'm a bit curious
how that's possible to trigger at compile time. Even if SBCL is
generating invalid code, it shouldn't SIGILL unless the IP points there, no?

> I'd love to have that issue resolved, but it is somewhat involved.  I need to teach SBCL how to detect the presence or absence of instructions sets, and provide different paths depending on what is available.  A side constraint is that the performance of machines with AVX2 should not deteriorate.  And then there is this really tricky issue of what to do in the case where code is compiled on a machine with AVX2, then save-lisp-and-die'd, and moved to a machine without AVX2.  So the instruction sets being used should probably be a property of the source code, with lexical scope, and not just a property of what is available on the machine that runs compile-file.
>
> I'll leave this issue open for others that run into the same problem.  And I'll think of a way to fix this properly in SBCL.  Thanks for reporting!

Sounds like an interesting problem. Hope it gets resolved; thanks for
looking at it and writing it up! That said, I do have access to a
computer with avx2 so this isn't a huge deal for me, but I suppose it'd
be an issue if someone wanted to actually start shipping software based on sb-simd.

**Comment by marcoheisig** [comment] 2022-01-06 10:55
Oh, I forgot that the bug already occurred at compile-time.  In that case the problem is probably due to constant folding.  SBCL calls functions known to be foldable already at compile-time in case all its arguments are constant.  And when there is a foldable function with a constant SIMD register of all ones, you run into the problem I described previously.

**Comment by marcoheisig** [comment] 2022-06-21 06:15
I'm closing this issue because sb-simd is now part of SBCL and this repository is being archived.

**Closed as completed by marcoheisig** 2022-06-21 06:15 UTC
